### ISSUE TITLE
Deploy app to github pages

### ISSUE THREAD

**Issue by jadjoubran** [kasperweidick/calculator#10]
It should be easy to deploy it, simply go to the settings page and set the `master` branch as the branch you want it to get deployed
https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by kasperweidick** [comment]
Managed to get it deployed on github pages, but i wont load my CSS and Javascript (see screenshot):
<img width="1439" alt="calculator" src="https://user-images.githubusercontent.com/43140588/49873134-6a8d0900-fe1b-11e8-9c44-fdefd42c85ba.png">

Also tried to force a rebuild but it doesn't really change anything.

**Comment by jadjoubran** [comment]
![screen shot 2018-12-12 at 17 01 09](https://user-images.githubusercontent.com/2265232/49881848-8e5a4a00-fe2f-11e8-8aee-ec2ab43d3b90.png)

can you guess why it's going out of kasperweidick all the way to the top? (that's why it's failing on github pages and working locally)

**Comment by kasperweidick** [comment]
Hehe I think I had to specify with a ./ that it had to look in the top directory, whichever that might be (so it works both locally and on github pages). It is working now! :-)

**Comment by kasperweidick** [comment]
How did you get that more detailed error message though?

**Comment by jadjoubran** [comment]
Awesome!
Hmm I'm honestly not sure, I originally had a cryptic error first, then did a hard reload and it worked
