### ISSUE TITLE
Checking which button was clicked

### ISSUE THREAD

**Issue by jadjoubran** [kasperweidick/calculator#12]
```javascript
event.currentTarget.innerHTML === `<i class="fas fa-times"></i>`
```

would tie your javascript to your markup (HTML), which might change later on and break your scripts
you could just add event listeners one by one to avoid checking the `.innerHTML` or you could add an `id` to every orange button and then check for the `id`

**Comment by kasperweidick** [comment]
<img width="615" alt="javascript_js_ _calculator" src="https://user-images.githubusercontent.com/43140588/49880288-1c343600-fe2c-11e8-87c5-c7a8792c5312.png">
Added id's to all the orange buttons and changed the code so they each have their own event listener. Somehow i just thought it would be better to not use too many id's and to not add event listeners individually.

**Comment by jadjoubran** [comment]
yeah as long as you don't check for innerHTML, both would work (either looping and adding eventlisteners and then checking ids or simply adding event listener per button)
