### ISSUE TITLE
Ignore node_modules

### ISSUE THREAD

**Issue by jadjoubran** [kasperweidick/calculator#9]
A best practice is to ignore pushing `node_modules`
when using starter projects, this is already setup for you, but it's nice to set it up yourself as well
so you want to create a new `.gitignore` file and add `node_modules`
however because you already committed this file to git, it's already **tracked** by git so you need to instruct git to forget about it
First answer in this [so](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore)

**Comment by kasperweidick** [comment]
I've added a .gitignore file with node_modules/ inside it and ran this command in the terminal: 
git rm -r --cached node_modules

Hope it was the right solution :-)

**Comment by jadjoubran** [comment]
yep correct 👍
